### PR TITLE
Feature/extended io

### PR DESCRIPTION
**Pull request by ahmidou**
Hi,
I took some times to move my extended IO stuff to the DFG, here's a first pass
with the Xfo type.

### CODE REVIEW

**Comment by mootzoid** [comment]
Hi Ahmidou,

Looks very good, thanks for taking the time!
Just one thing: I will have to revert the change you made in the Sconscript file as we are using VS2013 here to build the plugin.
Aside from that I'd say it's good to be merged into pablo.

One last question about the commit "started to add Properties IO":
This is still work in progress, right? Shall I better wait for it to be finished before merging or maybe only merge the first two commits, what do you think? I would prefer to not merge unfinished code.
Let me know.

Best,
Eric

**Comment by ahmidou** [comment]
Hi Eric,
Sorry about the Sconsscript, I started to setup everything in VS 2012
before noticing that 2013 was absolutely needed because
of one of the Fabric library dependency. I'll revert that in my code too.
You can definitely merge the two first commits, I'm not sure when I'll be
able to finish the properties yet.

Cheers.
-Ahmidou


2015-10-19 4:48 GMT-04:00 Eric Mootz <notifications@github.com>:

**Comment by mootzoid** [comment]
Hi Ahmidou,

apologies for the long silence. We were busy working on the Fabric 2.0.1 and the Xfo thing was pushed to 2.0.2.

Anyway, I am now working on things for 2.0.2 and today I will add the work you did for the Xfo support, finally :) I will however not merge this pull request but instead cherrypick the things I need or, possibly, add your work manually. In any case the next daily build of Fabric for Softimage should support Xfo ports!

I will keep you posted and when I'm done I will close this pull request if that's okay with you.

Cheers!
Eric

**Comment by mootzoid** [comment]
Hi again Ahmidou,

I finished implementing the support of Xfo ports.
You can close this pull request.

Thanks for your help!

Cheers,
Eric

**Comment by ahmidou** [comment]
No worries :)
I have a few more features to add when I'll get some times hopefully in a few weeks.

**Pull request closed without merging**
