### PR TITLE
1.15.2 extended io

### PR DESCRIPTION
**Pull request by ahmidou**
Hi, I've added some features to Splice, it's mostly more more IO types:
-native Xfo
-cluster properties (blendshapes, weight maps, envelopes)

and updated the "newSplice" command to force the initial IO to be and array by specifying the data type.
It also need an update for two KL extensions:
Xfo.kl
PolygonMeshDCCConversion.kl

I will send them to the support email.

Cheers
-A

### CODE REVIEW

**Comment by pzion** [comment]
@mootzoid @helgemathee Can you guys review and discuss, then get back to me?

**Comment by ahmidou** [comment]
Hey, did you had a chance to give it a look? I haven't looked at the Canvas
for Softimage plugin, but it might be good to have thoses features in 2.0.
Cheers
-A

2015-09-19 11:11 GMT-04:00 Peter Zion <notifications@github.com>:

**Comment by helgemathee** [comment]
@mootzoid this is in your hands. Note that we don't have a data type "Path", it's "FilePath". Be very careful reviewing this - and consider the effect of changes for 2.0.

**Comment by ahmidou** [comment]
Damned, the FilePath isn't implemented at all I should have remove it. Do
you want me to clean that and make a new pull request?
Sorry about that.

-A

2015-10-07 3:50 GMT-04:00 Helge Mathee <notifications@github.com>:

**Comment by mootzoid** [comment]
Hi Ahmidou,

first of all sorry we didn't yet look into this.
With the release of 2.0 we just didn't have time.

If you could clean the FilePath that would be great!

Cheers,
Eric

**Comment by mootzoid** [comment]
Hi Ahmidou,

we discussed internally about what to do with the pull request and decided to not merge it into rothko (nor pablo) as we are now officially on 2.0.

We did however file a ticket for this and will, some time in the future, integrate parts of it into Fabric 2.x.
Hope that makes sense!

Cheers!
Eric

**Comment by ahmidou** [comment]
Hi Eric, it totally make sense and that would be perfect to have it in 2.0.
I wish I had more time to move my code to it :(


2015-10-15 3:52 GMT-04:00 Eric Mootz <notifications@github.com>:

**Comment by reality3d** [comment]
Closing this pull request, since it is old

**Pull request closed without merging**
