### PR TITLE
Fixed linux build issues

### PR DESCRIPTION
**Pull request by aloysbaillet**
Mostly C++ correctness issues to do with passing non-const references to temporaries.

### CODE REVIEW

**Comment by pzion** [comment]
@mootzoid Looks fine to me, if it's good with you let me know and I will merge it and pull the changes into SceneGraph as well

**Comment by mootzoid** [comment]
@pzion Looks good to me, too. Please proceed :)

**Comment by pzion** [comment]
Thanks for the build fix!!

**Comment by aloysbaillet** [comment]
No problem, it's compiling and linking on linux, but not properly working there yet!

**Pull request merged**
